### ISSUE TITLE
blocksci_parser segmentation fault

### ISSUE THREAD

**Issue by azooo** [citp/BlockSci#37] opened 2017-12-28 18:09 UTC
Hello!

I am trying to get things going with blocksci (I am running a full bitcoin core node). When running blocksci_parser as indicated in the guide the following happened:

```
$ blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin
100.0% done fetching block headers
Starting with chain of 0 blocks
Removing 0 blocks
Adding 501332 blocks
1.41% done, Block 184396/501332
3.49% done, Block 212576/501332
Back linking transactions
99.96% done
3.94% done, Block 216881/501332Segmentation fault (core dumped)
```

If I now try to re-run the program, I get an exception

```
$ blocksci_parser --output-directory bitcoin-data update disk --coin-directory .bitcoin
100.0% done fetching block headers
Starting with chain of 217054 blocks
Removing 0 blocks
Adding 284318 blocks
0.00% done, Block 217055/501372terminate called after throwing an instance of 'NextQueueFinishedEarlyException'
  what():  Next queue finished early
Aborted (core dumped)
```
The whole issue is very much reproducible. I've tried to re-sync the BTC node, re-run blocksci_parser and the same thing happens.

Can someone explain to me what is happening here? Is there any workaround for this issue?

**Comment by shufps** [comment] 2017-12-30 07:50
Not enough memory? It needs about 60GB RAM.

**Comment by hkalodner** [comment] 2018-03-09 21:47
Whatever triggered the initial layer left the data in a corrupted state (which occurs basically any time the parser crashes mid-run). The later errors were caused by the data being in a corrupted state.

I'm not sure what triggered the original crash, it could have been a lack of memory or it could have been a bug in the parser. Unless this is reproduced in the new version, I'm going to assume that this is fixed with one of the more recent parser updates.

**Closed by hkalodner** 2018-03-09 21:47 UTC
