### ISSUE TITLE
Unable to run example: Transactions Paying over 1000 dollars in fees

### ISSUE THREAD

**Issue by freeskaro** [citp/BlockSci#101] opened 2018-05-03 10:44 UTC
So I installed BlockSci on my computer and parsed chain and started working through example problems. Here it didn't work. I don't know why its looking in a folder home/ubuntu/BlockSci.

%time high_fee_txes = chain.cpp.filter_tx("fee(tx) > 10000000", 0, len(chain))

CMake Error at CMakeLists.txt:38 (add_subdirectory):
  add_subdirectory given source "/home/ubuntu/BlockSci/libs/pybind11" which
  is not an existing directory.

CMake Error at CMakeLists.txt:42 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

make: *** No targets specified and no makefile found.  Stop.

make: *** No rule to make target 'install'.  Stop.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<timed exec> in <module>()

~/BlockSci/Notebooks/blocksci/__init__.py in filter_tx(self, code, start, end)
    225             filled_template = template.safe_substitute({"module_name":module_name, "func_def" : code})
    226             makefile = self.create_makefile(module_name)
--> 227             func = self.build_function(filled_template, makefile, module_name)
    228             self.saved_tx_filters[code] = func
    229         return self.saved_tx_filters[code](self.chain, start, end)

~/BlockSci/Notebooks/blocksci/__init__.py in build_function(self, full_code, makefile, module_name)
    252         out, err = process.communicate()
    253         print(err.decode('utf8'))
--> 254         mod = importlib.import_module(module_name)
    255         return getattr(mod, "func")

/usr/lib/python3.5/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.5/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.5/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.5/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ImportError: No module named 'dynamicCode6'

**Comment by hkalodner** [comment] 2018-05-03 19:27
This is a duplicate of #72. It is fixed in the new version which I'm about to pull into master.

**Closed by hkalodner** 2018-05-03 19:27 UTC
