### ISSUE TITLE
Python library import version mismatch

### ISSUE THREAD

**Issue by RCasatta** [citp/BlockSci#11] opened 2017-09-26 19:27 UTC
Hi,

after following the build instruction I want to try the python interface:
```
BlockSci/Notebooks$ python3
Python 3.5.2 (default, Aug 18 2017, 17:48:00)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/BlockSci/Notebooks/blocksci/__init__.py", line 1, in <module>
    from blocksci.blocksci_interface import *
ImportError: No module named 'blocksci.blocksci_interface'
```

in the directory blocksci I have a file `blocksci_interface.cpython-36m-x86_64-linux-gnu.so` which I think its supposed to satisfy the import but maybe something it's wrong

**Comment by darwin** [comment] 2017-09-26 19:52
Rename `blocksci_interface.cpython-36m-x86_64-linux-gnu.so` to `blocksci_interface.so`. It must be present in `Notebooks/blocksci`.

I ran into the same issue when compiling `blocksci_interface.so` against Python 3.6.x libraries under macOS 10.13.

**Comment by hkalodner** [comment] 2017-09-26 21:41
@RCasatta you're running into this problem since BlockSci's python library is being compiled against python 3.6 whereas you're running python version 3.5.2. Presumably you have multiple python installations on your machine. I'm not sure how pybind's cmake command controls which python version is selected by default, but it can be specified by adding `-DPYBIND11_PYTHON_VERSION=3.6` as a parameter to the `cmake`command.

This can be resolved by just renaming the file as @darwin suggested, but there's a chance that some incompatibilities would arise due to differences between python 3.5.2 and python 3.6.

@darwin you didn't specify what error you received when trying to import the python module. But I'm guessing that you ran into the same problem of multiple python installations.

I think the cleanest way to resolve this issue is to specify in the build process that pybind should compile a module against the python version which is found on the path by changing the`cmake` command to ``cmake --DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE:FILEPATH=`which python3` ..`` which will tell cmake to compile against whatever binary `python3` represents when it is run.

Could the two of you check if this resolves the issue? If so I'll close this out and modify the build instructions with this new command.

Thanks!

**Comment by darwin** [comment] 2017-09-26 22:16
I believe the problem is that by default `cmake` will compile blocksci_interface[.decoration].so, where decoration depends on python paths in the build environment.

In my case:
1. when `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` were pointing to Python 2.7 folders, it produced `blocksci_interface.so` without any decoration.
2. when `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY` were pointing to Python 3.6 folders, it produced `blocksci_interface.cpython-36m-darwin.so`

I believe the decoration is a function of python environment at hand.

**Comment by darwin** [comment] 2017-09-26 22:19
> you didn't specify what error you received 

I got the same `ImportError: No module named 'blocksci.blocksci_interface'`. Python interpreter expected `blocksci_interface.so` without decoration.

**Comment by darwin** [comment] 2017-09-26 22:21
> you're running into this problem since BlockSci's python library is being compiled against python 3.6 whereas you're running python version 3.5.2

That will be his next problem when python interpreter will be actually able to find and load `blocksci_interface.so`. But the error message will be different and descriptive. Exactly talking about a version mismatch.

**Comment by hkalodner** [comment] 2017-09-27 02:23
Yep, that all makes sense. The decoration is in place to protect against loading a version of the module compiled against a different version of the framework so I'd rather not eliminate that although I can if necessary. On systems where there's only one version of python there's no problem, but obviously that isn't a solution.

Sorry I wasn't very clear earlier when I said

> you didn't specify what error you received

I was really just wondering whether you were suffering from the same version mismatch issue as @RCasatta since your message hadn't specified which interpreter version you were running or the name of the library your machine was generating (Both of which I see you've specified now).

I think that the command I suggested ``cmake --DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE:FILEPATH=`which python3` ..`` should produce correct results for people assuming that they compile in the same enviroment that they run python from. It will select to compile against whatever version of the python interpreter is currently active as `python3`.

Does rerunning cmake with that command resolve the issue? I've modified the readme to clarify that python3 should be used when importing BlockSci. Hopefully with those changes the install process should be somewhat easier and clearer.

There's a definite need for expanded install instructions as well as usage instructions for BlockSci. I'm planning on moving over into developing documentation and usage examples further after the second major release (What is currently under development in the segwit branch).

**Comment by RCasatta** [comment] 2017-09-27 13:31
So, as pointed out If I launch the python3.6 executable the library loads.
I tried what @hkalodner suggested but the problem is `which python3` returns version 3.5
I think the problem in my system is that I have libpython for 3.6 and not for 3.5 as shown from the cmake output:
```
-- Found PythonInterp: /usr/bin/python3 (found version "3.5.2")
-- Found PythonLibs: /usr/local/lib/libpython3.6m.a
```

**Comment by hkalodner** [comment] 2017-09-27 14:58
@RCasatta Hmm interesting, I had been hoping that directing it to the correct interpreter version would help it find the correct library. 

Could you check if you have `/usr/local/lib/libpython3.5*` on your machine?

If so adding `-DPYBIND11_PYTHON_VERSION=3.5` to the `cmake` command should work. 

If you don't have the python3.5 development library installed then this appears to be a case of your machine not having the proper requirements installed, but `cmake` not recognizing that and failing as I would have hoped. In this case does it fail if you add the `-DPYBIND11_PYTHON_VERSION=3.5`?

This could end up being a pretty annoying issue for many people. When I add in a proper installation requirements section, this will hopefully clear up.

**Comment by darwin** [comment] 2017-09-27 15:37
btw. this is the cmake command-line I used for cmake to pickup my current python env on system paths

```bash
# see https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries
cmake --DCMAKE_BUILD_TYPE=Release \
  -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
  -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; import os; print(os.path.join(sysconfig.get_config_var('LIBDIR'), sysconfig.get_config_var('LDLIBRARY')))") \
  "$BLOCKSCI_DIR"
```

**Comment by darwin** [comment] 2017-09-27 15:43
> This could end up being a pretty annoying issue for many people. When I add in a proper installation requirements section, this will hopefully clear up.

I'm afraid it would be an uphill battle to teach people how to deal with jupyter/python/cmake/os/messy environments issues.

I would suggest preparing one canonical Dockerfile where you will have 100% control over whole stack in a single docker image. Actual source code could be mapped from host system. Blockchain data folders as well. Bitcoind and other RPC can be also mapped to be accessible inside the container. Also jupyter notebook server port can be exposed to the host machine so that people can easily play in the browser in their host machine. This would even work for people on Windows.

@hkalodner If you think this would be worth doing and you are not familiar with Docker, I volunteer to prepare initial setup and you can then tweak and document it as needed.

**Comment by RCasatta** [comment] 2017-09-27 15:59
> Could you check if you have /usr/local/lib/libpython3.5* on your machine?

No, I don't. But I followed the install instructions...
I tried to reinstall the package which should provide libpython3.5 but it tells me it's already installed
```
# apt install python3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.5.1-3).
```

**Comment by hkalodner** [comment] 2018-03-09 20:57
I'm gonna just call this a duplicate of #18. There's no direct bug here, but it's tricky to get the python versions to line up correctly and thus we could really benefit from encapsulating the install process rather than it being so manual like it is now.

**Closed by hkalodner** 2018-03-09 20:57 UTC
Labels: bug
