### ISSUE TITLE
inconsistencies with coinbase_tx using blocksci with litecoin

### ISSUE THREAD

**Issue by rg687** [citp/BlockSci#253] opened 2019-03-17 17:09 UTC
Hello, 

I have inconsistencies with coinbase_tx using blocksci with litecoin

chain.tx_with_hash('c88f4be224060580c8d45c1e862e397f414da1068a5c529077cfa0b4c9437b36').is_coinbase
>> True

This tx does not seem to be coinbased based on block explorers 
https://chainz.cryptoid.info/ltc/tx.dws?c88f4be224060580c8d45c1e862e397f414da1068a5c529077cfa0b4c9437b36.htm

--
chain.tx_with_hash('c88f4be224060580c8d45c1e862e397f414da1068a5c529077cfa0b4c9437b36').block.height
>> 1000323

(supposed to be block 785277)

--
chain.blocks[1000323].coinbase_tx.hash
>> c51558ce714ac97f987b51476b12aef2ee538f34bf81df6a014a01d785591fc6

(seems right but had similar problems when I parsed blocks looking for block.coinbase_tx, some tx returned were not coinbase)

#### System Information
BlockSci version: v0.6 from 03/17
Using AMI: yes/no no 
Total memory: 16 go

Thanks

**Comment by rg687** [comment] 2019-03-17 18:27
I just installed blocksci on another computer and problem does not occur with this specific tx. Not sure what happened and what caused the problem. I'll try to reparse the entire blockchain with the other computer see if it still occurs

**Comment by maltemoeser** [comment] 2019-03-19 17:29
Can't reproduce this using an older snapshot of 0.6 (a75bf9aa41894b2387460c33bc791ba0b589b529)

Will double-check with a newer version at a later point

**Comment by maltemoeser** [comment] 2019-03-26 00:31
Can't reproduce this on 90c442af9ea1727521279d5b00d683b122f0cd8b, maybe something got corrupted during the first parse

```python

In [4]: chain.tx_with_hash('c88f4be224060580c8d45c1e862e397f414da1068a5c529077cfa0b4c9437b36').is_coinbase                                                                                  
Out[4]: False

In [5]: chain.tx_with_hash('c88f4be224060580c8d45c1e862e397f414da1068a5c529077cfa0b4c9437b36').block.height                                                                                 
Out[5]: 785277

In [6]: chain.blocks[1000323].coinbase_tx.hash                                                                                                                                             
Out[6]: 28e2117ccd628334da03d29dce1078ba4fb5c88e95697fa3cf5986ddcc23ffc7
```

I'm closing this for now, feel to reopen it if it happens again

**Comment by rg687** [comment] 2019-03-31 14:37
Got a similar issue with btc chain.

>>> chain.blocks[372294].coinbase_tx.hash
d2f2c574e75ddb95104db3a20452f99b3f362a931f1ca56d40024daae4370dba
>>> chain.tx_with_hash('d2f2c574e75ddb95104db3a20452f99b3f362a931f1ca56d40024daae4370dba')
Tx(len(txins)=5, len(txouts)=2, size_bytes=815, block_height=409151, tx_index=125122660)

seems like something got corrupted while parsing but got no error message. (it used to work before and I feel like this is a one-time error that would not happen if i parse again)

How can i make sure that nothing got corrupted during the parsing? or do you know what could be causing it? ( this is a aws instance while the ltc error happened parsing on my laptop)

**Comment by maltemoeser** [comment] 2019-05-01 20:15
Haven't been able to reproduce these issues with any of my local parsings so far. If anyone wants to check their coinbase transactions (this should only return [known collisions](https://github.com/bitcoin/bips/blob/master/bip-0030.mediawiki)):

```python
for height, tx_hash in enumerate(chain.blocks.coinbase_tx.hash):
    tx = chain.tx_with_hash(tx_hash.decode('UTF-8'))
    if height != tx.block_height or not tx.is_coinbase:
        print(height, tx_hash.decode('UTF-8'))
```
> 91842 d5d27987d2a3dfc724e359870c6644b40e497bdc0589a033220fe15429d88599
> 91880 e3bf3d07d4b0375638d5f1db5255fe07ba2c4cb067cd81b84ee974b6585fb468


Referencing #161, as some consistency checks would be highly desirable in the parser

**Comment by rg687** [comment] 2019-06-06 10:49
Hello, 

I experience a similar inconsistency error with latest v0.6 ( 595ef0cf93bbd590ad8bac61f9440105b05c743f )

len(list(chain.address_from_string('LQKSRQbL8gKPWcj1Gqok8vXRxKM3eufcVg').out_txes)), len(list(chain.address_from_string('LQKSRQbL8gKPWcj1Gqok8vXRxKM3eufcVg').in_txes)), len(list(chain.address_from_string('LQKSRQbL8gKPWcj1Gqok8vXRxKM3eufcVg').txes)), chain.address_from_string('LQKSRQbL8gKPWcj1Gqok8vXRxKM3eufcVg').first_tx

returns 

(0,
 0,
 0,
 Tx(len(txins)=0, len(txouts)=1, size_bytes=114, block_height=218350, tx_index=580725))


I removed the data parsed and try again but same problem

**Comment by maltemoeser** [comment] 2019-06-06 11:53
```python
tx = chain.tx_with_hash("702b9100a397b1835cd7cb495c049dd30c5bb4770963c5d14274413077c8503c")
tx.ins[1].address
> PubkeyAddress(LQKSRQbL8gKPWcj1Gqok8vXRxKM3eufcVg)
```

The transaction sending to that address sends the funds to the raw pubkey, rather than the pubkey hash (address). Since there's no address format for pubkey outputs, most block explorers simply show the pubkey hash address. However, BlockSci distinguishes between these two types of addresses, and `address_from_string` will return the P2PKH variant, that's why you need to use `equiv()`

**Closed** 2019-08-23 18:20 UTC
Labels: data-corruption, litecoin, not-reproducible, parser
