### ISSUE TITLE
Disk mode not parsing all blocks

### ISSUE THREAD

**Issue by josconno** [citp/BlockSci#155] opened 2018-08-30 21:08 UTC
When I try to parse the Bitcoin block data, it doesn't recognize anything since May 29, 2018:

```
$ blocksci_parser --output-directory tmp-sync update disk --coin-directory .bitcoin
100.0% done fetching block headers
Starting with chain of 0 blocks
Removing 0 blocks
Adding 524997 blocks
```

It says "Adding 524997 blocks" despite my bitcoind installation showing that it has 539138 blocks:

```
$ bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 539138,
  "headers": 539138,
...
}
```

There are no other error messages or any indication something is wrong. I have tried completely reindexing the bitcoind database as well as erasing the parser output directory and starting over, with the same results. It refuses to index anything after this particular block.

**Comment by josconno** [comment] 2018-09-11 15:48
Turns out the issue was caused by a corrupted block received during my initial block download. Deleting the bad block and all after it, then redownloading the blocks fixed the issue.

**Comment by nomeata** [comment] 2018-09-15 21:12
Might this be a duplicate of #100? How could you tell which block was corrupt?

**Closed** 2019-01-17 20:57 UTC
Labels: parser
